# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        # Üstteki 4 buton için yatay layout
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Butonları ortalamak için boşluk ekle
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        
        # Üstteki 4 buton için font ayarları (15 punto)
        top_button_font = QtGui.QFont()
        top_button_font.setPointSize(15)  # Yazı boyutunu 15 punto yap
        
        # Butonları küçült ve ortala
        self.pushButton_dosya = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dosya.sizePolicy().hasHeightForWidth())
        self.pushButton_dosya.setSizePolicy(sizePolicy)
        self.pushButton_dosya.setFont(top_button_font)  # Fontu uygula
        self.pushButton_dosya.setDefault(True)
        self.pushButton_dosya.setObjectName("pushButton_dosya")
        self.horizontalLayout.addWidget(self.pushButton_dosya)
        
        self.pushButton_istatislik = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_istatislik.sizePolicy().hasHeightForWidth())
        self.pushButton_istatislik.setSizePolicy(sizePolicy)
        self.pushButton_istatislik.setFont(top_button_font)  # Fontu uygula
        self.pushButton_istatislik.setDefault(True)
        self.pushButton_istatislik.setObjectName("pushButton_istatislik")
        self.horizontalLayout.addWidget(self.pushButton_istatislik)
        
        self.pushButton_ara = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ara.sizePolicy().hasHeightForWidth())
        self.pushButton_ara.setSizePolicy(sizePolicy)
        self.pushButton_ara.setFont(top_button_font)  # Fontu uygula
        self.pushButton_ara.setDefault(True)
        self.pushButton_ara.setObjectName("pushButton_ara")
        self.horizontalLayout.addWidget(self.pushButton_ara)
        
        self.pushButton_yenikelime = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_yenikelime.sizePolicy().hasHeightForWidth())
        self.pushButton_yenikelime.setSizePolicy(sizePolicy)
        self.pushButton_yenikelime.setFont(top_button_font)  # Fontu uygula
        self.pushButton_yenikelime.setDefault(True)
        self.pushButton_yenikelime.setObjectName("pushButton_yenikelime")
        self.horizontalLayout.addWidget(self.pushButton_yenikelime)
        
        # Butonları ortalamak için boşluk ekle
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        
        # "Günlük Görevler" yazısını büyüt
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)  # Yazı boyutunu artır
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        
        # Altındaki 4 buton için grid layout
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        
        # Butonlar için font ayarları (30 punto)
        button_font = QtGui.QFont()
        button_font.setPointSize(30)  # Yazı boyutunu 30 punto yap
        
        # Butonları büyüt ve ortala
        self.pushButton_kart = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kart.sizePolicy().hasHeightForWidth())
        self.pushButton_kart.setSizePolicy(sizePolicy)
        self.pushButton_kart.setFont(button_font)  # Fontu uygula
        self.pushButton_kart.setDefault(True)
        self.pushButton_kart.setObjectName("pushButton_kart")
        self.gridLayout.addWidget(self.pushButton_kart, 0, 0, 1, 1)
        
        self.pushButton_test = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_test.sizePolicy().hasHeightForWidth())
        self.pushButton_test.setSizePolicy(sizePolicy)
        self.pushButton_test.setFont(button_font)  # Fontu uygula
        self.pushButton_test.setDefault(True)
        self.pushButton_test.setObjectName("pushButton_test")
        self.gridLayout.addWidget(self.pushButton_test, 0, 1, 1, 1)
        
        self.pushButton_eslestirme = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eslestirme.sizePolicy().hasHeightForWidth())
        self.pushButton_eslestirme.setSizePolicy(sizePolicy)
        self.pushButton_eslestirme.setFont(button_font)  # Fontu uygula
        self.pushButton_eslestirme.setDefault(True)
        self.pushButton_eslestirme.setObjectName("pushButton_eslestirme")
        self.gridLayout.addWidget(self.pushButton_eslestirme, 1, 0, 1, 1)
        
        self.pushButton_cumle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cumle.sizePolicy().hasHeightForWidth())
        self.pushButton_cumle.setSizePolicy(sizePolicy)
        self.pushButton_cumle.setFont(button_font)  # Fontu uygula
        self.pushButton_cumle.setDefault(True)
        self.pushButton_cumle.setObjectName("pushButton_cumle")
        self.gridLayout.addWidget(self.pushButton_cumle, 1, 1, 1, 1)
        
        self.verticalLayout_2.addLayout(self.gridLayout)
        
        # Kaydet butonu (font boyutunu 15 punto yap)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_kaydet = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_kaydet.sizePolicy().hasHeightForWidth())
        self.pushButton_kaydet.setSizePolicy(sizePolicy)
        self.pushButton_kaydet.setFont(top_button_font)  # Fontu uygula (15 punto)
        self.pushButton_kaydet.setDefault(True)
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.horizontalLayout_2.addWidget(self.pushButton_kaydet)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        self.menuAyarlar = QtWidgets.QMenu(self.menubar)
        self.menuAyarlar.setObjectName("menuAyarlar")
        self.menuDark_mode = QtWidgets.QMenu(self.menuAyarlar)
        self.menuDark_mode.setObjectName("menuDark_mode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWhite = QtWidgets.QAction(MainWindow)
        self.actionWhite.setObjectName("actionWhite")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.menuDark_mode.addAction(self.actionWhite)
        self.menuDark_mode.addAction(self.actionDark)
        self.menuAyarlar.addAction(self.menuDark_mode.menuAction())
        self.menubar.addAction(self.menuAyarlar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_dosya.setText(_translate("MainWindow", "Dosya"))
        self.pushButton_istatislik.setText(_translate("MainWindow", "İstatislik"))
        self.pushButton_ara.setText(_translate("MainWindow", "Ara"))
        self.pushButton_yenikelime.setText(_translate("MainWindow", "Yeni Kelime"))
        self.label.setText(_translate("MainWindow", "Gunluk Gorevler"))
        self.pushButton_cumle.setText(_translate("MainWindow", "Cümle Oluşturma"))
        self.pushButton_eslestirme.setText(_translate("MainWindow", "Eşleştirme"))
        self.pushButton_kart.setText(_translate("MainWindow", "Kelime Kartları"))
        self.pushButton_test.setText(_translate("MainWindow", "Test"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.menuAyarlar.setTitle(_translate("MainWindow", "Ayarlar"))
        self.menuDark_mode.setTitle(_translate("MainWindow", "Tema"))
        self.actionWhite.setText(_translate("MainWindow", "White"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())